### ISSUE TITLE
More details about PERSONAL_GITHUB_TOKEN

### ISSUE THREAD

**Issue by arthurlogilab** [muesli/readme-scribe#1]
The documentation should probably mention which permissions PERSONAL_GITHUB_TOKEN needs to have. Not entirely sure this is right but I got it working with : 

```
 PERSONAL_GITHUB_TOKEN — read:org, read:packages, read:public_key, read:repo_hook, read:user, repo:status 
```

Thanks a for a nice project ! My profile is up https://github.com/arthurlogilab/ !

**Comment by muesli** [comment]
It depends a bit which features you access from the templating language. For example accessing sponsors needs different permissions than just retrieving your recently created projects. We should probably add documentation for each method and the scope it operates on. We can also refer to the GitHub documentation here.

**Comment by drupol** [comment]
Indeed, it should be documented.

**Comment by drupol** [comment]
Thanks!
