### ISSUE TITLE
Additionnal step about copying PERSONAL_GITHUB_TOKEN in project Secrets

### ISSUE THREAD

**Issue by arthurlogilab** [muesli/readme-scribe#2]
I think the documentation is missing the step where you copy your token to Secrets of your $LOGIN repo. 

:heart: the project !

**Comment by muesli** [comment]
@arthurlogilab Do you think `Now create a new secret in your repository's Settings and enter that token.` is not clear enough?

**Comment by arthurlogilab** [comment]
Re-reading the documentation I realised the information was there. Maybe having two steps could make it clearer for people that don't use these types of settings everyday  ?

**Comment by muesli** [comment]
The visual alignment isn't great, but I feel like it's belonging to the second step where you generate the actual token. I'll see if I can improve that.
