### ISSUE TITLE
Find a way to not disturb the "contributions" heatmap 

### ISSUE THREAD

**Issue by arthurlogilab** [muesli/readme-scribe#5]
Since I've setup readme-scribe (and although I tried to change the autor of the commit message) my graph looks like this : 

![Screenshot from 2020-11-05 16-05-02](https://user-images.githubusercontent.com/445200/98258352-11836c80-1f81-11eb-8bdd-415dec297fd1.png)

It would be nice to a way to avoid turning the entire calendar green even for days when no contributions were done. 

One way is to remove the fast moving parts (in my case the mastodon feed)... but if there's another way that would be nice!

**Comment by muesli** [comment]
Are you sure? I think it's not doing that for me since your PR: https://github.com/muesli/readme-scribe/pull/3

**Comment by benleb** [comment]
@arthurlogilab you also removed the user info of the committer from the workflow, maybe that's the problem?

**Comment by arthurlogilab** [comment]
You're right, sorry for the noise, I applied the patch on my personnal github account https://github.com/arthurlutz but forgot to do it here... 

![Screenshot from 2020-11-06 09-18-07](https://user-images.githubusercontent.com/445200/98342698-15f76600-2011-11eb-8e82-f8d3742af753.png)

**Comment by muesli** [comment]
@arthurlogilab No worries, happens to the best of us. Thanks for confirming!
