### ISSUE TITLE
action fails

### ISSUE THREAD

**Issue by Hope-IT-Works** [muesli/readme-scribe#6]
Hey, i don't get it to work.
I know, GitHub isn't for support and stuff, but you seem to understand this much more than i do.

The action is failing over and over. 
https://github.com/Hope-IT-Works/Hope-IT-Works/runs/1773246181
![image](https://user-images.githubusercontent.com/52013820/105922649-56c4b100-603b-11eb-9199-07304c507aa0.png)

I don't understand why.

I created a new personal access token at https://github.com/settings/tokens
![image](https://user-images.githubusercontent.com/52013820/105922247-94750a00-603a-11eb-90f7-24b13f06e2a8.png)

Then i added the given token to the action secrets in the repository settings
![image](https://user-images.githubusercontent.com/52013820/105922419-f33a8380-603a-11eb-82e5-836574494d5c.png)

You can check my [action](https://github.com/Hope-IT-Works/Hope-IT-Works/blob/main/.github/workflows/readme-scribe.yml) (did not change anything) and my [template](https://github.com/Hope-IT-Works/Hope-IT-Works/blob/main/templates/README.md.tpl)

Do you know what's wrong?

Thanks in advance,
Tobi

**Comment by muesli** [comment]
This is probably because the default GitHub branch name has changed from `master` to `main`.

In `readme-scribe.yml` change `branch: master` to `branch: main` accordingly. I'll update the docs to reflect the new default.
