### ISSUE TITLE
Push new Docker image?

### ISSUE THREAD

**Issue by markphelps** [muesli/readme-scribe#7]
It seems that https://github.com/muesli/markscribe/pull/25 was merged, however the readme-scribe action and Docker image do not seem to have been updated with the latest master?

Would you be able to publish a new Docker image with latest master of `markscribe`?

Also, it would be great if you could add versioning to the Docker image via tags that correspond with `markscribe` releases, and then allow for specifying a version when using `readme-scribe`

**Comment by muesli** [comment]
The docker image matches the latest stable release, in this case v0.4.0, which is indeed 3 commits behind master.

I agree tho, Docker tags would be nice. I'll have to automate the entire Docker build process a bit more.

**Comment by markphelps** [comment]
Ah my bad, I thought the last stable release was more recent. 

Let me know if I can help with the docker automation

**Comment by muesli** [comment]
Just a heads up: I've just released markscribe v0.5.0 and pushed a matching Docker image as well!

Of course I'd appreciate help with the docker automation! Two things come to mind here: we should try and integrate building the regular, tagged stable releases with our existing GoReleaser workflow. Additionally we could automatically build and push the latest state from git-master with a GitHub Action as a separate docker tag.
