### ISSUE TITLE
Actions fails with updated PERSONAL_GITHUB_TOKEN

### ISSUE THREAD

**Issue by Hope-IT-Works** [muesli/readme-scribe#8]
Hey, GitHub updated their token format, i got the following e-mail:

![image](https://user-images.githubusercontent.com/52013820/122657322-d83feb80-d162-11eb-8508-6c87483bf5f6.png)

I regenerated my PERSONAL_GITHUB_TOKEN and now the readme-scribe action fails.
As you can see here:
https://github.com/Hope-IT-Works/Hope-IT-Works-old/runs/2866477695

Do you have an idea on how to fix that problem?
Is it something you need to fix in the action or do i need to fix something in my settings?
The action previously ran through.

Thanks in advance and have a nice weekend,
Tobi | @Hope-IT-Works

**Comment by muesli** [comment]
Did you update the `PERSONAL_GITHUB_TOKEN` secret in your repository to match the new token?

**Comment by Hope-IT-Works** [comment]
The token has the same name as before.

Greetings,
Tobi | @Hope-IT-Works

**Comment by drupol** [comment]
Same issue on my profile: https://github.com/drupol/drupol/actions

**Comment by muesli** [comment]
@Hope-IT-Works @drupol I can't reproduce that yet. Did you also update the secret in your repository's settings (`Secrets` -> `Repository Secrets`)?

**Comment by drupol** [comment]
While making screenshot for this issue, I noticed that the secret I was using was wrong. 

I renamed it properly and everything is fine now.

However, it would be nice to update the documentation and list the permission the token need to have.

**Comment by Hope-IT-Works** [comment]
@muesli Thank you for your hint. I could fix the action.

The following steps are required to fix this issue:

1. Open your token settings at [https://github.com/settings/tokens](https://github.com/settings/tokens)
2. Click on your `PERSONAL_GITHUB_TOKEN`
3. Regenerate your token by pressing the button **[Regenerate token]**
4. Copy your token from the text field or by pressing the copy-to-clipboard button
5. Open your repository settings and open the secrets page
e. g.: `https://github.com/YOUR_NAME/YOUR_NAME/settings/secrets/actions`
6. Update your `PERSONAL_GITHUB_TOKEN` token by pressing the button **[Update]**
7. Paste your token and save it by pressing **[Update secret]**

After that, the action should run through.
By default, the branch must be named `main`!

Thanks for the help, have a nice week!
Tobi | @Hope-IT-Works
