### ISSUE TITLE
Optional dash in listed projects

### ISSUE THREAD

**Issue by feluxerich** [muesli/readme-scribe#9]
When I have a project without a description there is still displayed the `-`. Like `myFancyProjectName -`. I'd be very proud of you if you could fix this.

**Comment by muesli** [comment]
You can absolutely do that with the template language, I just didn't want the example to be too convoluted.

Try something like:
```
- [{{.Name}}]({{.URL}}){{ with .Description }} - {{ . }}{{ end }}
```
